apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: sam3232333/config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7777
          envFrom:
            - secretRef:
                name: config-server-secret
          env:
            - name: EUREKA_URL
              value: http://eureka-server:8761/eureka/