apiVersion: v1
kind: Secret
metadata:
  name: config-server-secret
type: Opaque
stringData:
  CONFIG_REPO_URI: https://github.com/sam1212111/timesheet-management-system
  CONFIG_REPO_USERNAME: sam1212111
  CONFIG_REPO_TOKEN: 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
